In [2]:
import numpy as np

In [2]:
x_pixel = np.arange(0,8)
print(x_pixel)

[0 1 2 3 4 5 6 7]


In [3]:
# 1.5베 확대한다 가정

x_zoom = x_pixel * 1.5
print(x_zoom) # 이렇게 하면 픽셀이 없어짐. hole 이라고 함.

[ 0.   1.5  3.   4.5  6.   7.5  9.  10.5]


In [4]:
x_zoomed = np.arange(0, 12) # 미리 있다고 가정함
print(x_zoomed)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [6]:
x_original = x_zoomed / 1.5
print(x_original.round(2)) # 빠지는 픽셀은 없음. 문제는 이상한 값이 생김.

[0.   0.67 1.33 2.   2.67 3.33 4.   4.67 5.33 6.   6.67 7.33]


In [4]:
import numpy as np
import cv2
import sys

In [7]:
img = cv2.imread('./fig/ch2_fig/puppy.bmp', 0)
img1 = img.copy()

cv2.imshow('img', img)

while True:
    key = cv2.waitKey()

    if key == 27:
        break
    elif key == ord('i'):
        img = 255 - img
        cv2.imshow('img', img)
    elif key == ord('e'):
        img = cv2.Canny(img, 50, 150)
        cv2.imshow('img', img)
    elif key == ord('r'):
        img = img1.copy()
        cv2.imshow('img', img)
    


cv2.waitKey()
cv2.destroyAllWindows()

### 동영상

In [14]:
cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print('Video open failed')
    sys.exit()

w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(cap.get(cv2.CAP_PROP_FPS))
fourcc = cv2.VideoWriter_fourcc(*'DIVX')

out = cv2.VideoWriter('review.avi', fourcc, fps*0.7, (w, h))

while True:
    ret, frame = cap.read()

    if not ret:
        print('Frame read failed')
        break
    edge = cv2.Canny(frame, 20, 100)
    edge = cv2.cvtColor(edge, cv2.COLOR_GRAY2BGR)

    out.write(edge)

    cv2.imshow('frame', frame)
    cv2.imshow('edge', edge)

    if cv2.waitKey(30) == 27:
        break

cap.release()
out.release()
cv2.destroyAllWindows()

In [29]:
img = np.ones((600, 1200, 3), np.uint8) * 255

cv2.line(img, (100, 100), (300, 100), (0, 0, 255), 10)
cv2.arrowedLine(img, (300, 100), (250, 300), (255, 0, 0), 10, cv2.LINE_AA)
cv2.rectangle(img, (200, 400), (400, 500), (0, 255, 0), -1)
cv2.rectangle(img, (220, 420, 160, 60), (0, 255, 255), 10)
cv2.circle(img, (600, 300), 100, (0, 0, 255), 10, cv2.LINE_AA)
cv2.putText(img, 'Once upon a time', (300, 300), cv2.FONT_HERSHEY_DUPLEX, 2, (0, 0, 0), 2, cv2.LINE_AA)


cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

### 알파채널

In [54]:
src = cv2.imread('./fig/ch2_fig/imgbin_hat.png', cv2.IMREAD_UNCHANGED)
dst = cv2.imread('./fig/ch2_fig/puppy.bmp')


h, w = dst.shape[:2]
src = cv2.resize(src, (w//2, h//2), cv2.INTER_AREA)

src_hat = src[:, :, :-1]
src_mask = src[:, :, :1]

h1, w1 = src_hat.shape[:2]

dst_crop = dst[100:100+h1, 200:200+w1]

cv2.copyTo(src_hat, src_mask, dst_crop)

cv2.imshow('dst', dst)

cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
import os

In [ ]:
img_list = os.listdir('./fig/my_images/')
img_paths = []
for i in img_list:
    img_path = './fig/my_images/' + i
    img_paths.append(img_path)

print(img_paths)

cv2.namedWindow('img', cv2.WINDOW_NORMAL)
cv2.setWindowProperty('img', cv2.WND_PROP_FULLSCREEN, cv2.WINDOW_FULLSCREEN)

idx = 0

while True:
    img = cv2.imread(img_paths[idx])
    
    if img is None:
        print('imgage load failed')
        sys.exit()
    
    cv2.imshow('img', img)

    if cv2.waitKey(3000) == 27:
        break
    idx += 1
    if idx >= len(img_paths):
        idx = 0
    cv2.destroyAllWindows()


### 동영상(키 입력)

In [4]:
cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print('open failed')
    sys.exit()

f_flag = False
i_flag = False

while True:
    ret, frame = cap.read()

    if not ret:
        print('frame read failed')
        break
    if f_flag == True:
        frame = cv2.flip(frame, 1)
    if i_flag == True:
        frame = cv2.Canny(frame, 50, 150)

    cv2.imshow('frame', frame)

    key = cv2.waitKey(20)
    
    if key == 27:
        break
    elif key == ord('f'):
        f_flag = not f_flag
    elif key == ord('i'):
        i_flag = not i_flag

    
cap.release()
cv2.destroyAllWindows()

### 마우스 콜백

In [ ]:
def call_mouse(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        print(f'left button clicked = {x}, {y}')
    elif event == cv2.EVENT_LBUTTONUP:
        print(f'left button up = {x}, {y}')
    elif event == cv2.EVENT_MOUSEMOVE:
        if flags == cv2.EVENT_FLAG_LBUTTON:
            print(f'moving = {x}, {y}')




img = np.ones((480, 640, 3), np.uint8) * 255

cv2.namedWindow('img')
cv2.setMouseCallback('img', call_mouse, img)

cv2.imshow('img', img)

cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
def call_mouse(event, x, y, flags, param):
    global old_x, old_y
    global color, thik
    if event == cv2.EVENT_LBUTTONDOWN:
        old_x , old_y = x, y
    elif event == cv2.EVENT_MOUSEMOVE:
        if flags == cv2.EVENT_FLAG_LBUTTON:
            cv2.line(img, (old_x, old_y), (x, y), color, thik, cv2.LINE_AA)
            cv2.imshow('img', img)
            old_x, old_y = x, y

img = np.ones((600,600,3), np.uint8) * 255

cv2.namedWindow('img')
cv2.setMouseCallback('img', call_mouse, img)

color = (0,0, 255)
thik = 4

while True:
    cv2.imshow('img', img)
    key = cv2.waitKey()
    if key == 27:
        break
    elif key == ord('s'):
        cv2.imwrite('./fig/save_img.png', img) # 이미지 저장 방법
        print('image was saved')
    elif key == ord('1'):
        color = (255, 0, 0)
    elif key == ord('2'):
        color = (0, 255, 0)
    elif key == ord('3'):
        color = (0, 0, 255)
    elif key == ord('4'):
        color = (255, 255, 255)
    elif key == ord('5'):
        color = (0, 0, 0)
    elif key == ord('+'):
        thik += 1
    elif key == ord('-'):
        thik -= 1

cv2.destroyAllWindows()